### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application 

### ISSUE THREAD

**Issue by KevinFabregas** [ptrpfa/vitalsource-crawler#1]
Hi I'm having this problem. What am I doing wrong
Traceback (most recent call last):
  File "D:\Lithub\crawler.py", line 9, in <module>
    browser = Firefox (executable_path = gecko_driver_file, options = opts)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by ptrpfa** [comment]
Hi @KevinFabregas the program was made to run on Linux so it may have some issues running on Windows. You may try looking here to resolve your issue: https://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application
Hope this helps!

**Comment by KevinFabregas** [comment]
> Hi @KevinFabregas the program was made to run on Linux so it may have some issues running on Windows. You may try looking here to resolve your issue: https://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application
> Hope this helps!

Thank you very much, now I fixed it. And it is really working.
